language: node_js
node_js:
  - 'stable'
git:
  depth: 1
git:
  submodules: false
script:
   - yarn lint
   - yarn test-ci
   - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi'
